- platform: template
  covers:
    bedroom_closet_window_for_homekit:
      unique_id: bedroom_closet_window_for_homekit
      friendly_name: "Bedroom Closet Window"
      value_template: > 
        {% from 'utils.jinja' import invert_cover_state %}
        {{ invert_cover_state(states('cover.bedroom_closet_window')) }} 
      position_template: "{{ state_attr('cover.bedroom_closet_window', 'current_position') | int }}"
      device_class: window
      open_cover:
        action: cover.open_cover
        target: 
          entity_id: cover.bedroom_closet_window
      close_cover: 
        action: cover.close_cover
        target:
          entity_id: cover.bedroom_closet_window
      stop_cover: 
        action: cover.stop_cover
        target:
          entity_id: cover.bedroom_closet_window
      set_cover_position: 
        action: cover.set_cover_position
        target:
          entity_id: cover.bedroom_closet_window
        data:
          position: "{{ position }}"
      icon_template: >-
          {% if is_state('sensor.bedroom_closet_window_closed', 'open') %}
            mdi:window-open
          {% else %}
            mdi:window-closed
          {% endif %}


