
# Loads default set of integrations. Do not remove.
default_config:

my:

wake_on_lan:

rest_command:
  peloton_fan_power_ir:
    url: "http://10.3.1.42/send.htm?remote=Vornado&command=POWER"
  peloton_fan_plus_ir:
    url: "http://10.3.1.42/send.htm?remote=Vornado&command=PLUS"
  peloton_fan_minus_ir:
    url: "http://10.3.1.42/send.htm?remote=Vornado&command=MINUS"

logger:
  default: info
  logs:
    homeassistant.components.mqtt: warning
#    custom_components.nut: debug
    custom_components.pyscript: info
    custom_components.pyscript.file.relative_humidity_correction: info

recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
      - alexa
      - zigbee2mqtt_networkmap
      - camera
      - update
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*
      - sensor.router*
      - sensor.sun*
      - binary_sensor.230i*
      - sensor.ap_*
      - sensor.*_voltage
      - sensor.*_power_factor
      - sensor.*_apparent_power
      - sensor.*_reactive_power
      - sensor.door*
      - sensor.home_assistant*
      - sensor.*_write_rate
      - sensor.*_storage_used
      - sensor.*_link_speed
      - sensor.*_current_total
      - sensor.*_power_total
      - sensor.nvr*
      - sensor.*_lqi
      - sensor.*_uptime*
      - sensor.*_free_mem
      - sensor.*_signal
      - sensor.*_rssi
      - sensor.*link_quality
      - sensor.*_last_seen
      - sensor.*cpu*
      - sensor.*memory*
      - sensor.toothbrush*
      - sensor.*_clients
      - sensor.*_connect_count
      - sensor.g5_ptz_*
      - sensor.garage_exterior*
    entities:
      - camera.front_door
      - sensor.home_assistant_v2_db
      - sensor.memory_free
      - sensor.memory_use
      - sensor.memory_use_percent
      - sensor.processor_use
      - weather.openweathermap
      - sensor.paio
      - sensor.ham
      - sensor.bacon
      - sensor.carpaccio
      - sensor.thao_s_phone
      - sensor.thao_s_watch
      - sensor.aaron_s_watch
      - sensor.kitchen_fan_plug_total_energy
      - sensor.kitchen_fan_plug_current
      - sensor.kitchen_fan_plug_voltage

logbook:
  include:
    domains:
      - automation
      - light
      - lock
      - scene
      - script
      - sensor
      - switch
      - template
      - cover
      - fan
      - alexa
  exclude:
    entity_globs:
      - sensor.uptime*
      - sensor.*_uptime*
      - sensor.g5_ptz*
      - sensor.garage_exterior*


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

  extra_module_url:
    - /config/www/community/bar-card/bar-card.js
    - /config/www/community/custom-sidebar

# Text-to-speech
tts:
  - platform: google_translate

lovelace:
  # Add yaml dashboards
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    lovelace-yaml:
      mode: yaml
      title: Control
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: dashboards.yaml


  # mode: yaml
  # resources:
  #   - url: /local/zigbee2mqtt-networkmap.js?v=0.8.0
  #     type: module


# mqtt:
  # sensor:
  #   - name: Zigbee2mqtt Networkmap
  #     # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
  #     state_topic: zigbee2mqtt/bridge/response/networkmap
  #     value_template: >-
  #       {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  #     # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
  #     json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
  #     json_attributes_template: "{{ value_json.data.value | tojson }}"



automation: !include automations.yaml
fan: !include_dir_merge_list fans/
light: !include_dir_merge_list lights/
lock: !include_dir_merge_list locks/
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
template: !include_dir_merge_list template_devices/
cover: !include_dir_merge_list windows/
shell_command: !include shell_commands.yaml



