- platform: template
  name: Front Door
  unique_id: lock.front_door
  value_template: "{{ is_state('switch.buzzer', 'off') }}"
  lock:
    action: switch.turn_off
    target:
      entity_id: switch.buzzer
  unlock:
    action: switch.turn_on
    target:
      entity_id: switch.buzzer
