
- platform: mqtt_room
  unique_id: ham_beacon
  device_id: ham
  name: 'ham'
  state_topic: 'espresense/devices/ham'
  timeout: 10
  away_timeout: 120
- platform: mqtt_room
  unique_id: aaron_watch_beacon
  device_id: "irk:b24f3ff7555b01621abc1cd1afb84c86"
  name: 'Aaron''s Watch'
  state_topic: 'espresense/devices/irk:b24f3ff7555b01621abc1cd1afb84c86'
  timeout: 10
  away_timeout: 120
- platform: mqtt_room
  unique_id: thaos_watch_beacon
  device_id: "irk:ee71e93d0a46a148e6188515f7906234"
  name: 'Thao''s Watch'
  state_topic: 'espresense/devices/irk:ee71e93d0a46a148e6188515f7906234'
  timeout: 10
  away_timeout: 120    
- platform: mqtt_room
  unique_id: thaos_phone_beacon
  device_id: thao_s_phone
  name: 'Thao''s Phone'
  state_topic: 'espresense/devices/thao_s_phone'
  timeout: 10
  away_timeout: 120  
- platform: mqtt_room
  unique_id: bacon_beacon
  device_id: irk:c8651874e52a42996f780a6d2d5383a2
  name: 'bacon'
  state_topic: 'espresense/settings/irk:c8651874e52a42996f780a6d2d5383a2'
  timeout: 10
  away_timeout: 120  
- platform: mqtt_room
  unique_id: carpaccio_beacon
#    device_id: carpaccio
#  device_id: "irk:c8651874e52a42996f780a6d2d5383a2"
  device_id: "irk:69d09726e042001efd137ed5fce39bd1"
  name: 'carpaccio'
#    state_topic: 'espresense/devices/carpaccio'
#  state_topic: 'espresense/devices/irk:c8651874e52a42996f780a6d2d5383a2'
  state_topic: 'espresense/devices/irk:69d09726e042001efd137ed5fce39bd1'
  timeout: 10
  away_timeout: 120 
