
- platform: mqtt_room
  unique_id: aarons_watch_beacon
  device_id: aarons_watch
  name: 'aaron''s watch'
  state_topic: 'espresense/devices/aarons_watch'
  timeout: 10
  away_timeout: 120

- platform: mqtt_room
  unique_id: thaos_watch_beacon
  device_id: !secret thaos_watch_irk
  name: 'thao''s watch'
  state_topic: !secret thaos_watch_topic
  timeout: 10
  away_timeout: 120    

- platform: mqtt_room
  unique_id: ham_beacon
  device_id: ham
  name: 'ham'
  state_topic: 'espresense/devices/ham'
  timeout: 10
  away_timeout: 120

- platform: mqtt_room
  unique_id: thaos_phone_beacon
  device_id: thaos_phone
  name: 'thao''s phone'
  state_topic: 'espresense/devices/thao_s_phone'
  timeout: 10
  away_timeout: 120  

- platform: mqtt_room
  unique_id: bacon_beacon
  device_id: bacon
  name: 'bacon'
  state_topic: 'espresense/devices/bacon'
  timeout: 10
  away_timeout: 120  

- platform: mqtt_room
  unique_id: carpaccio_beacon
  device_id: carpaccio
  name: 'carpaccio'
  state_topic: 'espresense/devices/carpaccio'
  timeout: 10
  away_timeout: 120 

- platform: mqtt_room
  unique_id: paio_beacon
  device_id: paio
  name: 'paio'
  state_topic: 'espresense/devices/paio'
  timeout: 10
  away_timeout: 120

