
substitutions:
  temperature_1_id: temperature_1
  temperature_1_name: "Temperature 1"
  temperature_1_offset: "0.0"
  temperature_1_gain: "1.0"
  moisture_1_id: moisture_1
  moisture_1_name: "Moisture 1"
  moisture_1_min_value: "350"
  moisture_1_max_value: "1015"
  temperature_2_id: temperature_2
  temperature_2_name: "Temperature 2"
  temperature_2_offset: "0.0"
  temperature_2_gain: "1.0"
  moisture_2_id: moisture_2
  moisture_2_name: "Moisture 2"
  moisture_2_min_value: "350"
  moisture_2_max_value: "1015"
  temperature_3_id: temperature_3
  temperature_3_name: "Temperature 3"
  temperature_3_offset: "0.0"
  temperature_3_gain: "1.0"
  moisture_3_id: moisture_3
  moisture_3_name: "Moisture 3"
  moisture_3_min_value: "350"
  moisture_3_max_value: "1015"
  temperature_4_id: temperature_4
  temperature_4_name: "Temperature 4"
  temperature_4_offset: "0.0"
  temperature_4_gain: "1.0"
  moisture_4_id: moisture_4
  moisture_4_name: "Moisture 4"
  moisture_4_min_value: "350"
  moisture_4_max_value: "1015"
  update_interval: 10s



sensor:
  - platform: adafruit_soil_sensor
    address: 0x36
    temperature:
      id: ${temperature_1_id}
      name: ${temperature_1_name}
      offset: ${temperature_1_offset}
      gain: ${temperature_1_gain}
    moisture:
      id: ${moisture_1_id}
      name: ${moisture_1_name}
      min_value: ${moisture_1_min_value}
      max_value: ${moisture_1_max_value}
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    update_interval: ${update_interval}
  - platform: adafruit_soil_sensor
    address: 0x37
    temperature:
      id: ${temperature_2_id}
      name: ${temperature_2_name}
      offset: ${temperature_2_offset}
      gain: ${temperature_2_gain}
    moisture:
      id: ${moisture_2_id}
      name: ${moisture_2_name}
      min_value: ${moisture_2_min_value}
      max_value: ${moisture_2_max_value}
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    update_interval: ${update_interval}
  - platform: adafruit_soil_sensor
    address: 0x38
    temperature:
      id: ${temperature_3_id}
      name: ${temperature_3_name}
      offset: ${temperature_3_offset}
      gain: ${temperature_3_gain}
    moisture:
      id: ${moisture_3_id}
      name: ${moisture_3_name}
      min_value: ${moisture_3_min_value}
      max_value: ${moisture_3_max_value}
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    update_interval: ${update_interval}
  - platform: adafruit_soil_sensor
    address: 0x39
    temperature:
      id: ${temperature_4_id}
      name: ${temperature_4_name}
      offset: ${temperature_4_offset}
      gain: ${temperature_4_gain}
    moisture:
      id: ${moisture_4_id}
      name: ${moisture_4_name}
      min_value: ${moisture_4_min_value}
      max_value: ${moisture_4_max_value}
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    update_interval: ${update_interval}


