display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    R1_pin: 42
    G1_pin: 41
    B1_pin: 40
    R2_pin: 38
    G2_pin: 39
    B2_pin: 37
    A_pin:
      number: 45
      ignore_strapping_warning: true
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    brightness: 100
    update_interval: 8ms
    i2sspeed: HZ_20M
    latch_blanking: 1
#    driver: ICN2038S
    clock_phase: false
    rotation: 0
