defaults:
  sda: SDA
  scl: SCL
  i2c_frequency: 800kHz
  board_type: esp32dev
  log_level: INFO

packages:
  device_base: !include 
    file: common.yaml
    vars:
      log_level: ${log_level}

esp32:
  board: ${board_type}
  framework:
    type: arduino

i2c:
  - id: bus_a
    sda: $sda
    scl: $scl
    frequency: $i2c_frequency
    scan: true
    setup_priority: 700