defaults:
  sda: SDA
  scl: SCL
  i2c_frequency: 800kHz
  board_type: esp32dev

packages:
  device_base: !include common.yaml

esp32:
  board: ${board_type}
  framework:
    type: arduino

i2c:
  - id: bus_a
    sda: $sda
    scl: $scl
    frequency: $i2c_frequency
    scan: true
    setup_priority: 700