substitutions:
  i2c_frequency: 800kHz
  board_type: adafruit_feather_esp32s2
  sda_pin: GPIO3
  scl_pin: GPIO4
  neopixel_pin: GPIO33
  neopixel_power_pin: GPIO21


packages:
  device_base: !include esp32.yaml
  wifi: !include wifi.yaml
  neo: !include neopixel.yaml


esphome:
  platformio_options:
    board_build.flash_mode: dio


spi: 
  clk_pin: 
    number: GPIO36
  mosi_pin: 
    number: GPIO35
  miso_pin: 
    number: GPIO37


switch:
  - platform: gpio
    id: i2c_power
    restore_mode: ALWAYS_ON
    pin: 
      number: GPIO7


status_led:
  pin:
    number: GPIO13
    inverted: false

