substitutions:
  board_type: adafruit_feather_esp32s3

packages:
  device_base: !include 
    file: esp32.yaml
    vars:
      sda: GPIO3
      scl: GPIO4
  wifi: !include wifi.yaml
  neo: !include 
    file: neopixel.yaml
    vars:
      power_pin: GPIO21
      neopixel_pin: GPIO33


spi: 
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12
