substitutions:
  board_type: adafruit_feather_esp32s3
  i2c_frequency: 800kHz
  sda_pin: GPIO3
  scl_pin: GPIO4
  neopixel_pin: GPIO33
  neopixel_power_pin: GPIO21

packages:
  device_base: !include esp32.yaml
  wifi: !include wifi.yaml
  neo: !include neopixel.yaml


i2c:
  - id: !extend bus_a
    sda:
      ignore_strapping_warning: true


spi: 
  clk_pin: 
    number: GPIO14
  mosi_pin: 
    number: GPIO13
  miso_pin: 
    number: GPIO12


switch:
  - platform: gpio
    id: i2c_power
    restore_mode: ALWAYS_ON
    pin: GPIO7

