substitutions:
  board_type: adafruit_feather_esp32s3
  i2c_frequency: 800kHz

packages:
  device_base: !include 
    file: esp32.yaml
    vars:
      sda: GPIO3
      scl: GPIO4
      i2c_frequency: $i2c_frequency
      board_type: $board_type
  wifi: !include wifi.yaml
  neo: !include 
    file: neopixel.yaml
    vars:
      power_pin: GPIO21
      neopixel_pin: GPIO33

i2c:
  - id: !extend bus_a
    sda:
      ignore_strapping_warning: true



spi: 
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12


switch:
  - platform: gpio
    id: i2c_power
    restore_mode: ALWAYS_ON
    pin: GPIO7

