defaults:
  power_pin: GPIO8
  neopixel_pin: GPIO5

switch:
  - platform: gpio
    id: neopix_power
    restore_mode: ALWAYS_ON
    pin: 
      number: ${power_pin}


light:
 - platform: neopixelbus
   id: neopixel_led
   type: GRB
   variant: WS2812
   pin: 
     number: ${neopixel_pin}
   num_leds: 1
   name: "NeoPixel"