defaults:
  i2c_frequency: 800kHz

substitutions:
  board_type: adafruit_qtpy_esp32

packages:
  device_base: !include 
    file: esp32.yaml 
    vars:
      sda: GPIO22
      scl: GPIO19
      i2c_frequency: $i2c_frequency
  wifi: !include wifi.yaml


spi: 
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12
