substitutions:
  i2c_frequency: 800kHz
  board_type: adafruit_qtpy_esp32s3_nopsram
  neopixel_pin: GPIO39
  neopixel_power_pin: GPIO38

packages:
  device_base: !include 
    file: esp32.yaml 
    vars:
      sda: GPIO41
      scl: GPIO40
      i2c_frequency: $i2c_frequency
  wifi: !include wifi.yaml
  neo: !include neopixel.yaml
  

spi: 
  clk_pin: 
    number: GPIO36
  mosi_pin: 
    number: GPIO35
  miso_pin: 
    number: GPIO37


