substitutions:
  board_type: adafruit_qtpy_esp32
  i2c_frequency: 800kHz
  neopixel_pin: GPIO5
  neopixel_power_pin: GPIO8
  sda_pin: GPIO22
  scl_pin: GPIO19

packages:
  device_base: !include esp32.yaml 
  wifi: !include wifi.yaml
  # unsupported in esphome until esp32-pico gets explicit support
  neo: !include neopixel.yaml

# esp32:
#   variant: esp32

switch: !extend neopixel_power
  pin:
    ignore_pin_validation_error: true

spi:
  clk_pin: 
    number: GPIO14
  mosi_pin: 
    number: GPIO13
  miso_pin: 
    number: GPIO12
    ignore_strapping_warning: true
