substitutions:
  i2c_frequency: 800kHz
  board_type: adafruit_qtpy_esp32s3_nopsram
  neopixel_pin: GPIO39
  neopixel_power_pin: GPIO38
  sda_pin: GPIO41
  scl_pin: GPIO40

packages:
  device_base: !include esp32.yaml
  wifi: !include wifi.yaml
  neo: !include neopixel.yaml
  
# esphome: 
#   platformio_options:
#     board: adafruit_qtpy_esp32s3_nopsram

spi: 
  clk_pin: 
    number: GPIO36
  mosi_pin: 
    number: GPIO35
  miso_pin: 
    number: GPIO37


