substitutions:
  sgp4x_nox_id: nox
  sgp4x_nox_name: "NOX"
  sgp4x_voc_id: voc
  sgp4x_voc_name: "VOC"
  sgp4x_temperature_source: temperature
  sgp4x_humidity_source: humidity

sensor:
  - platform: sgp4x
    id: sgp4x_sensor
    i2c_id: bus_a
    address: 0x59
    update_interval: 1s
    store_baseline: true
    compensation:
      temperature_source: ${sgp4x_temperature_source}
      humidity_source: ${sgp4x_humidity_source}
    nox:
      id: ${sgp4x_nox_id}
      name: ${sgp4x_nox_name}
      accuracy_decimals: 1
      # filters:
      #   - sliding_window_moving_average:
      #       window_size: 15
      #       send_every: 15
      #       send_first_at: 5
      #   - filter_out: 65535
    voc:
      id: ${sgp4x_voc_id}
      name: ${sgp4x_voc_name}
      accuracy_decimals: 1
      # filters:
      #   - sliding_window_moving_average:
      #       window_size: 15
      #       send_every: 15
      #       send_first_at: 5
      #   - filter_out: 65535

logger:
  logs:
    sgp4x: INFO