substitutions:
  device_description: "Sonoff S31 Smart Plug"
  project_name: "Sonoff.S31 Smart Plug"
  project_version: "v1.0.0"
  button_gpio: GPIO0
  relay_gpio: GPIO12
  board_type: esp12e


packages:
  device_base: !include esp8266.yaml
  plug: !include smart_plug_common.yaml
  cse7766: !include cse7766.yaml
  wifi: !include wifi.yaml

