substitutions:
  display_name: st7789v
  backlight: GPIO26
  st7789_cs_pin: GPIO14
  st7789_dc_pin: GPIO27
  st7789_reset_pin: GPIO33
  st7789_backlight_pin: GPIO26
  st7789_width: "172"
  st7789_height: "320"
  st7789_offset_height: "34"
  st7789_offset_width: "0"
  st7789_rotation: "90"
  st7789_update_interval: 0.5s

output:
  - platform: ledc
    id: backlight_output
    pin: 
      number: ${st7789_backlight_pin}

light:
  - platform: monochromatic
    output: backlight_output
    name: "Backlight"
    restore_mode: ALWAYS_ON
    default_transition_length: 0.1s

display:
  - platform: st7789v
    id: ${display_name}
    model: Custom
    cs_pin: 
      number: ${st7789_cs_pin}
    dc_pin: 
      number: ${st7789_dc_pin}
    reset_pin: 
      number: ${st7789_reset_pin}
    height: ${st7789_height}
    width: ${st7789_width}
    offset_height: ${st7789_offset_height}
    offset_width: ${st7789_offset_width}
    rotation: ${st7789_rotation}
#    backlight_pin: GPIO26
    update_interval: ${st7789_update_interval}