output:
  - platform: ledc
    id: backlight_output
    pin: ${backlight}

light:
  - platform: monochromatic
    output: backlight_output
    name: "Backlight"
    restore_mode: ALWAYS_ON
    default_transition_length: 0.1s

display:
  - platform: st7789v
    model: Custom
    cs_pin: 
      number: ${cspin}
      ignore_pin_validation_error: true
    dc_pin: ${dcpin}
    reset_pin: ${resetpin}
    height: 320
    width: 172
    offset_height: 34
    offset_width: 0
    rotation: 90
#    backlight_pin: GPIO26
    id: ${name}
    update_interval: 0.5s