substitutions:
  dns_domain: sf.aberrant.org
  board_type: wesp32
  sda_pin: GPIO15
  scl_pin: GPIO4


defaults:
  fqdn: ${hostname}.${dns_domain}

packages:
  device_base: !include esp32.yaml

i2c:
  - id: !extend bus_a
    sda: 
      ignore_strapping_warning: true


ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0
  phy_registers:
    - address: 0x10
      value: 0x1FFA
      page_id: 0x07

  use_address: ${fqdn}