- platform: template
  fans:
    bedroom_purifier:
      unique_id: bedroom_purifier
      friendly_name: "Bedroom Purifier"
      speed_count: 5
      value_template: "{{ states('input_boolean.bedroom_purifier_power_state') }}"
      preset_mode_template: "{{ states('input_select.bedroom_purifier_preset') }}"
      preset_modes:
        - "Silent"
        - "Low"
        - "Medium"
        - "High"
        - "Turbo"
      turn_on:
        - service: input_button.press
          data:
            entity_id: input_button.bedroom_purifier_on
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.bedroom_purifier_power_state  
      turn_off:
        - service: input_button.press
          data:
            entity_id: input_button.bedroom_purifier_off
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.bedroom_purifier_power_state  
      set_preset_mode:
        - service: input_button.press
          data:
            entity_id: >
              {% from 'utils.jinja' import concat %}
              {{ concat('input_button.bedroom_purifier_', preset_mode) }}        
        - service: input_boolean.turn_{{ 'on' if preset_mode != Off else 'off' }}
          data:
            entity_id: input_boolean.bedroom_purifier_power_state

        - condition: "{{ preset_mode != Off }}"
        - service: input_select.select_option
          target:
            entity_id: input_select.bedroom_purifier_preset
          data:
            option: "{{ preset_mode }}"

    
    bedroom_purifier_for_homekit:
      unique_id: bedroom_purifier_for_homekit
      friendly_name: "Bedroom Purifier"
      value_template: "{{ states('fan.bedroom_purifier') }}"
      preset_mode_template: "{{ states('input_select.bedroom_purifier_speed') }}"
      percentage_template: >-
        {% from 'utils.jinja' import preset_5_speed_to_percent %}
        {{ preset_5_speed_to_percent(states('input_select.bedroom_purifier_preset')) }}
      speed_count: 5
      turn_on:
        service: fan.turn_on
        data:
          entity_id: fan.bedroom_purifier
      turn_off:
        - service: fan.turn_off
          data:
            entity_id: fan.bedroom_purifier
      set_percentage:
        - service: fan.set_preset_mode
          target:
            entity_id: fan.bedroom_purifier
          data:
            preset_mode: >
              {% from 'utils.jinja' import percent_to_5_speed %}
              {{ percent_to_5_speed(percentage) }}
