- platform: template
  fans:
    kitchen_fan:
      unique_id: kitchen_fan
      friendly_name: "Kitchen Fan"
      value_template: "{{ states('sensor.kitchen_fan_plug_current') | float(0) > 0.1 }}"
      direction_template: "{{ states('input_select.kitchen_fan_direction') }}"
      speed_count: 5
      preset_mode_template: "{{ states('input_select.kitchen_fan_speed') }}"
      preset_modes:
        - "Off"
        - "Low"
        - "Medium"
        - "High"
        - "Turbo"
      turn_on:
        - action: input_button.press
          data:
            entity_id: input_button.kitchen_fan_on          
      turn_off:
        - action: input_button.press
          data:
            entity_id: input_button.kitchen_fan_off
      set_direction:
        action: input_select.select_option
        target:
          entity_id: input_select.kitchen_fan_direction
        data:
          option: "{{ direction }}"
      set_preset_mode:
        - action: input_button.press
          data:
            entity_id: >
              {% from 'utils.jinja' import concat %}
              {{ concat('input_button.kitchen_fan_', preset_mode) }}
        - action: input_select.select_option
          target:
            entity_id: input_select.kitchen_fan_speed
          data:
            option: "{{ preset_mode }}"


    kitchen_fan_for_homekit:
      unique_id: kitchen_fan_for_homekit
      friendly_name: "Kitchen Fan"
      value_template: "{{ states('fan.kitchen_fan') }}"
      direction_template: "{{ states('input_select.kitchen_fan_direction') }}"
      percentage_template: >
        {% from 'utils.jinja' import preset_4_speed_to_percent %}
        {{ preset_4_speed_to_percent(states('input_select.kitchen_fan_speed')) }}      
      speed_count: 4
      turn_on:
        action: fan.turn_on
        data:
          entity_id: fan.kitchen_fan
      turn_off:
        - action: fan.turn_off
          data:
            entity_id: fan.kitchen_fan
      set_direction:
        action: fan.set_direction
        target:
          entity_id: fan.kitchen_fan
        data:
          direction: "{{ direction }}"
      set_percentage:
        - action: fan.set_preset_mode
          target:
            entity_id: fan.kitchen_fan
          data:
            preset_mode: >
              {% from 'utils.jinja' import percent_to_4_speed %}
              {{ percent_to_4_speed(percentage) }}
              

