- platform: template
  fans: 
    litter_box_fan:
      unique_id: litter_box_fan
      friendly_name: Litter Box Fan
      value_template: "{{ states('switch.litter_box_fan') }}"
      speed_count: 1
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.litter_box_fan
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.litter_box_fan