- platform: template
  fans:
    living_room_purifier:
      unique_id: living_room_purifier_2
      friendly_name: "Living Room Purifier Old"
      speed_count: 5
      value_template: "{{ states('input_boolean.living_room_purifier_power_state') }}"
      preset_mode_template: "{{ states('input_select.living_room_purifier_preset') }}"
      preset_modes:
        - "Silent"
        - "Low"
        - "Medium"
        - "High"
        - "Turbo"
      turn_on:
        - action: input_button.press
          data:
            entity_id: input_button.living_room_purifier_on
        - action: input_boolean.turn_on
          data:
            entity_id: input_boolean.living_room_purifier_power_state  
      turn_off:
        - action: input_button.press
          data:
            entity_id: input_button.living_room_purifier_off
        - action: input_boolean.turn_off
          data:
            entity_id: input_boolean.living_room_purifier_power_state  
      set_preset_mode:
        - action: input_button.press
          data:
            entity_id: >
              {% from 'utils.jinja' import concat %}
              {{ concat('input_button.living_room_purifier_', preset_mode) }}        
        - action: input_boolean.turn_{{ 'on' if preset_mode != Off else 'off' }}
          data:
            entity_id: input_boolean.living_room_purifier_power_state

        - condition: "{{ preset_mode != Off }}"
        - action: input_select.select_option
          target:
            entity_id: input_select.living_room_purifier_preset
          data:
            option: "{{ preset_mode }}"

    
    living_room_purifier_for_homekit:
      unique_id: living_room_purifier_for_homekit
      friendly_name: "Living Room Purifier"
      value_template: "{{ states('fan.living_room_purifier') }}"
      percentage_template: "{{ states('fan.living_room_purifier')|int(0) }}"
#      preset_mode_template: "{{ states('input_select.living_room_purifier_speed') }}"
#      percentage_template: >-
#        {% from 'utils.jinja' import preset_5_speed_to_percent %}
#        {{ preset_5_speed_to_percent(states('input_select.living_room_purifier_preset')) }}
      speed_count: 5
      turn_on:
        action: fan.turn_on
        data:
          entity_id: fan.living_room_purifier
      turn_off:
        - action: fan.turn_off
          data:
            entity_id: fan.living_room_purifier
      set_percentage:
        - action: fan.set_percentage
          target:
            entity_id: fan.living_room_purifier
          data:
            percentage: "{{ percentage }}"
        # - action: fan.set_preset_mode
        #   target:
        #     entity_id: fan.living_room_purifier
        #   data:
        #     preset_mode: >
        #       {% from 'utils.jinja' import percent_to_5_speed %}
        #       {{ percent_to_5_speed(percentage) }}
