substitutions:
  device_name: bedroom-air-quality
  friendly_name: Bedroom Air Quality
  board_type: adafruit_feather_esp32s3
  fqdn: air-quality-bedroom.sf.aberrant.org

packages:
  device_base: !include 
    file: common/esp32.yaml
    vars:
      sda: GPIO41
      scl: GPIO40
      i2c_frequency: 50kHz
      board_type: $board_type
  wifi: !include common/wifi.yaml
  pmsa: !include common/pmsa003i.yaml
  dp: !include common/dew_point.yaml
  neo: !include 
    file: common/neopixel.yaml
    vars:
      power_pin: GPIO38
      neopixel_pin: GPIO39


sensor:
  - platform: scd4x
    i2c_id: bus_a
    address: 0x62
    update_interval: 5s
    co2:
      name: "CO2"
      id: co2
      on_value:
        - then:
            - lambda: |-
                auto call = id(neopixel_led).turn_on();
                Color co2RGB = aqiColor(round(x));
                call.set_rgb((float)co2RGB.r/255.0, (float)co2RGB.g/255.0, (float)co2RGB.b/255.0);
        - then: 
            - light.turn_on:
                id: neopixel_led
                transition_length: 0.5s
                brightness: 15%
                red: !lambda |- 
                  Color co2RGB = co2Color(round(x));
                  return (float)co2RGB.r / 255.0;
                green: !lambda |- 
                  Color co2RGB = co2Color(round(x));
                  return (float)co2RGB.g / 255.0;
                blue: !lambda |- 
                  Color co2RGB = co2Color(round(x));
                  return (float)co2RGB.b / 255.0;
    temperature:
      name: "Temperature"
      id: temperature
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      id: humidity
      accuracy_decimals: 1
  
