substitutions:
  name: bedroom-presence
  friendly_name: Bedroom Presence
  room: Bedroom
  hostname: presence-bedroom
  device_description: "Bedroom Presence Sensor"
  pir_delay_off: "10s"
  occupancy_delay_off: "15s"

packages:
  device_base: !include common/everything_presence_one.yaml
  wifi: !include common/wifi.yaml

