esphome:
  name: bedroom-closet-window
  friendly_name: Bedroom Closet Window

esp8266:
  board: huzzah

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "lGNx/i1V2APmDMUrlVFVSSOTllR+pVUgV2ev9bgtAHw="

ota:
  password: "8b0a0dab912534cf4803fac186b58d8f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Closet-Window"
    password: "nMTlPKRAX80a"
  manual_ip:
    static_ip: 10.3.1.73
    gateway: 10.3.1.2
    subnet: 255.255.0.0

captive_portal:
    

status_led:
  pin: 
    number: GPIO0
    inverted: False


# fan:
#   - platform: binary
#     id: bedroom_closet_fans
#     name: Bedroom Closet Fans
#     icon: mdi:fan
#     output: fan_power_relay
#     on_turn_on:
#       - if:
#           condition: 
#             binary_sensor.is_on: window_closed_sensor
#           then:
#             - cover.open: bedroom_closet_window
#             - delay: 5s
#       - output.turn_on: fan_power_relay
      # lambda: |-
      #   if (id(window_closed_sensor).state) {
      #     auto window = id(bedroom_closet_window).make_call();
      #     window.set_command_open();
      #     window.perform();
      #     delay(5000);
      #     id(fan_power_relay).turn_on();
      #   }
      #   else {
      #     id(fan_power_relay).turn_on();
      #   }
#     on_turn_off:
#         - output.turn_off: fan_power_relay


switch:
  - platform: template
    id: bedroom_closet_fans
    name: Bedroom Closet Fans
    icon: mdi:fan
    lambda: 'return id(fan_power_relay).state;'
    turn_on_action:
      - if:
          condition:
            or:
              - binary_sensor.is_on: window_closed_sensor
              - binary_sensor.is_off: window_open_sensor_2
          then:
            - cover.open: bedroom_closet_window
            - delay: 6s
      - if:
          condition:
            and:
              - binary_sensor.is_off: window_closed_sensor
              - binary_sensor.is_on: window_open_sensor_2
          then:
            - switch.turn_on: fan_power_relay
      - if:
          condition:
            or:
              - binary_sensor.is_on: window_closed_sensor
              - binary_sensor.is_off: window_open_sensor_2
          then:
            - homeassistant.service:
                service: notify.notify
                data:
                  title: Closet Fans Error
    turn_off_action:
      - switch.turn_off: fan_power_relay

  - platform: gpio
    id: window_open_switch
    restore_mode: ALWAYS_OFF
    pin: GPIO5
    internal: true
    interlock: [window_close_switch]

  - platform: gpio
    id: window_close_switch
    restore_mode: ALWAYS_OFF
    pin: GPIO4
    internal: true
    interlock: [window_open_switch]

  - platform: gpio
    id: fan_power_relay
    pin: GPIO15
    internal: true

binary_sensor:
  - platform: gpio
    id: unused1
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: false
    internal: true

  - platform: gpio
    id: window_closed_sensor
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true
    
  - platform: gpio
    id: window_open_sensor
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true
    
  - platform: gpio
    id: closet_motion
    name: Closet Motion
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: false
      inverted: false
    internal: false

  - platform: template
    id: bedroom_closet_window_open
    lambda: 'return !id(window_closed_sensor).state;'
    name: Window Closed
    icon: mdi:window
    device_class: window

  - platform: homeassistant
    name: Zigbee Window Sensor
    id: window_open_sensor_2
    entity_id: binary_sensor.bedroom_closet_window_sensor
    internal: false


cover:
  - platform: endstop
    id: bedroom_closet_window
    name: "Bedroom Closet Window"

    open_action:
      - switch.turn_on: window_open_switch
    open_duration: 16.7s
    open_endstop: window_open_sensor

    close_action:
      - switch.turn_on: window_close_switch
      - switch.turn_off: bedroom_closet_fans
    close_duration: 16.2s
    close_endstop: window_closed_sensor
    on_closed:
      - switch.turn_on: window_close_switch
      - delay: 0.5s
      - switch.turn_off: window_close_switch

    stop_action:
      - switch.turn_off: window_close_switch
      - switch.turn_off: window_open_switch
    max_duration: 20s