esphome:
  name: compressor-plug
  friendly_name: Compressor Plug
  platform: ESP8266
  board: esp01_1m


logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: WARN # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

uart:
  rx_pin: RX
  baud_rate: 4800

# Enable Home Assistant API
api:
  encryption:
    key: "a8HsI3sWdpHgwJGZG3GPz4oZfIZ/oYOhL2G93XXZ0gA="

ota:
  - platform: esphome
    password: "7b0bf391470ec95fbf6ed1f40c66363f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: plug-compressor.sf.aberrant.org

  # manual_ip:
  #   static_ip: 10.3.1.99
  #   gateway: 10.3.1.2
  #   subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Compressor-Plug Fallback Hotspot"
#    password: "8zsqqWcngGZh"

#captive_portal:
  

# Device Specific Config

button:
  - platform: restart
    name: "Restart"
    entity_category: "CONFIG"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 1
#      filters:
#        - throttle_average: 60s
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
#      filters:
#        - throttle_average: 60s
    power:
      name: "Power"
      accuracy_decimals: 1
      id: my_power
#      filters:
#        - throttle_average: 60s
#    energy:
#      name: "Total Energy"
#      accuracy_decimals: 1
#      filters:
#        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "Apparent Power"
#      filters:
#        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "Power Factor"
      accuracy_decimals: 1
#      filters:
#        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "Total Energy"
    power_id: my_power
    accuracy_decimals: 1

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True