substitutions:
  device_name: crawl-space-sensor
  friendly_name: Crawl Space
  board_type: adafruit_feather_esp32s3
  fqdn: sensor-crawl-space.sf.aberrant.org

packages:
  device_base: !include 
    file: common/esp32.yaml
    vars:
      sda: GPIO3
      scl: GPIO4
  wifi: !include common/wifi.yaml
  temperature: !include common/bme280.yaml
  neo: !include 
    file: common/neopixel.yaml
    vars:
      power_pin: GPIO21
      neopixel_pin: GPIO33

esphome:
  platformio_options:
    board_build.flash_mode: dio


bluetooth_proxy:
  active: True


