substitutions:
  name: crawl-space-sensor
  friendly_name: Crawl Space
  hostname: sensor-crawl-space
  room: "Crawl Space"
  device_description: "Crawl Space Temperature Sensor"



packages:
  device_base: !include common/feather_esp32s3.yaml
  temperature: !include common/bme280.yaml



# bluetooth_proxy:
#   active: True


