substitutions:
  device_name: crawl-space-sensor
  friendly_name: Crawl Space
  fqdn: sensor-crawl-space.sf.aberrant.org

packages:
  device_base: !include 
    file: common/feather_esp32s3.yaml
  temperature: !include common/bme280.yaml


# bluetooth_proxy:
#   active: True


