esphome:
  name: crawl-space-sensor
  friendly_name: Crawl Space
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: adafruit_feather_esp32s3
  variant: esp32s3
  framework:
    type: arduino
#    type: esp-idf
# Enable logging
logger:

bluetooth_proxy:
  active: True

# Enable Home Assistant API
api:
  encryption:
    key: "QD4MxL9tkGKnsHtolc9T+LFX7cPDjW8ohm62hN6w5Ig="

ota:
  platform: esphome
  password: "5e433d328bde62b744c9ef63a40ad03d"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: crawl-space-sensor.sf.aberrant.org

  # manual_ip:
  #   static_ip: 10.3.1.37
  #   gateway: 10.3.1.2
  #   subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
 # ap:
 #   ssid: "crawl-space-sensor"
 #   password: "3YNltoMmXWXn"

#captive_portal:
    
button:
  - platform: restart
    name: "Restart"
    entity_category: "CONFIG"

i2c:
  - id: bus_a
    sda: GPIO3
    scl: GPIO4
#    frequency: 100000Hz
    frequency: 800kHz
    scan: true
    setup_priority: 700


sensor:
  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x77
    temperature:
      id: temperature
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"

switch:
  - platform: gpio
    id: neopix_power
    restore_mode: ALWAYS_ON
    pin: GPIO21


#light:
 # - platform: neopixelbus
 #   id: neopixel_led
  #  type: GRB
  #  variant: WS2812
  #  pin: GPIO33
   # num_leds: 1
  #  name: "NeoPixel"
