substitutions:
  name: kitchen-presence
  friendly_name: Kitchen Presence
  hostname: presence-kitchen
  room: "Kitchen"
  device_description: "Kitchen Presence Sensor"


packages:
#  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
  device_base: !include common/athom_presence_sensor.yaml
  wifi: !include common/wifi.yaml
  common: !include common/common.yaml

