esphome:
  name: kitchen-fan-plug
  friendly_name: Kitchen Fan Plug

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  encryption:
    key: "HhfmSX4Sgber3JJ/bn7+10trhekNg/YgeYP20bmCgoA="

ota:
  password: "845c91be6229f0d3add3ba3fb689facf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 10.3.1.90
    gateway: 10.3.1.2
    subnet: 255.255.0.0


# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

button:
  - platform: restart
    name: "Restart"
    entity_category: "CONFIG"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 1s
    current:
      name: "Current"
      accuracy_decimals: 1
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    power:
      name: "Power"
      accuracy_decimals: 1
      id: my_power
  - platform: total_daily_energy
    name: "Total Energy"
    power_id: my_power

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True