substitutions:
  friendly_name: Litter Box Fan

esphome:
  name: plug-litter-box-fan
  friendly_name: Litter Box Fan
  name_add_mac_suffix: false

packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml

api:
  encryption:
    key: vl4qRqnqJfMFViZ6LoyjMYlMu6k3ZCEHzo6UO+HCGZI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.3.1.98
    gateway: 10.3.1.2
    subnet: 255.255.0.0

logger:
  #level: DEBUG
   level: INFO