substitutions:
  name: living-room-presence
  friendly_name: Living Room Presence
  room: "Living Room"
  device_description: "Living Room Presence Sensor"
  hostname: presence-livingroom

packages:
#  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
  device_base: !include common/athom_presence_sensor.yaml
  wifi: !include common/wifi.yaml
  common: !include common/common.yaml