substitutions:
  name: "living-room-presence"
  friendly_name: Living Room Presence

packages:
  Athom_Technology.Presence_Sensor: github://asolochek/athom-configs/athom-presence-sensor.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: D6Gwtb4MiBqoIvn7/y7PDrF+CzFkcB4bspZmKRMax2k=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.3.1.76
    gateway: 10.3.1.2
    subnet: 255.255.0.0

logger:
  #level: DEBUG
   level: INFO