substitutions:
  name: matrix-display
  friendly_name: Matrix Display
  hostname: matrix-display
  room: Office
  device_description: "Matrix Display"
  

packages:
  device_base: !include common/matrixportal_esp32s3.yaml
  display: !include common/adafruit_64x32_2pt5mm_led_matrix.yaml
  fonts: !include common/fonts.yaml
  colors: !include common/colors.yaml


display: 
  - id: !extend matrix
    lambda: |-
      it.strftime(8, 8, id(eight_bit_dragon16), matrix_light_green, "%H:%M", id(ha_time).now());

# it.print(1, 0, id(eight_bit_dragon1), red, "12345678");
# it.printf(1, 10, id(jetbrains_mono), green, "12345678");
# it.printf(1, 20, id(terminus12n), blue, "12345678");

#      it.strftime(0, 0, id(small_dot), "%Y-%m-%d", id(ha_time).now());
#      it.strftime(0, 10, id(square_dot), "%H:%M", id(ha_time).now());


#      it.printf(0, 0, id(gomme), "HELLO");