substitutions:
  name: office-presence
  friendly_name: "Office Presence"
  room: "Office"
  hostname: presence-office
  device_description: "Office Presence Sensor"
  pir_delay_off: "10s"
  occupancy_delay_off: "15s"

packages:
  device_base: !include common/everything_presence_one.yaml
  wifi: !include common/wifi.yaml
