substitutions:
  device_name: office-air-quality
  friendly_name: Office Air Quality
  fqdn: air-quality-office.sf.aberrant.org

packages:
  device_base: !include 
    file: common/qtpy_esp32.yaml
    vars:
      i2c_frequency: 50kHz
  fonts: !include common/fonts.yaml
  scd: !include common/scd4x.yaml
  pmsa: !include common/pmsa003i.yaml
  dp: !include common/dew_point.yaml
  display: !include
    file: common/st7789v.yaml
    vars:
      name: office_display
      backlight: GPIO26
      dcpin: GPIO27
      cspin: GPIO7
      resetpin: GPIO15


display:
  - id: !extend office_display
    lambda: |-
      unsigned int co2_val = round(id(co2).state);
      unsigned int aqi_val = round(id(aqi).state);

      Color aqiRGB = aqiColor(aqi_val);
      Color co2RGB = co2Color(co2_val); 

      it.printf(40, 0, id(futura32), "%.1f°F     %.1f%%", c_to_f(id(temperature).state), id(humidity).state);
      it.printf(0, 56, id(futura32), "AQI:");
      it.printf(100, 40, id(futura60), Color(aqiRGB), " %d", aqi_val);
      it.printf(2, 120, id(futura32), "CO");
      it.printf(52, 140, id(futura16), "2");
      it.printf(62, 120, id(futura32), ":");
      it.printf(100, 104, id(futura60), Color(co2RGB), " %d", co2_val);
  

