substitutions:
  name: office-air-quality
  friendly_name: Office Air Quality
  room: Office
  hostname: air-quality-office
  device_description: "Office Air Quality Monitor"
  i2c_frequency: 50kHz
  display_name: office_display
  st7789_backlight_pin: GPIO26
  st7789_dc_pin: GPIO27
  st7789_cs_pin: GPIO7
  st7789_reset_pin: GPIO15

packages:
  device_base: !include common/qtpy_esp32.yaml
  fonts: !include common/fonts.yaml
  scd: !include common/scd4x.yaml
  pmsa: !include common/pmsa003i.yaml
  dp: !include common/dew_point.yaml
  display: !include common/st7789v.yaml



display:
  - id: !extend ${display_name}
    reset_pin:
      ignore_strapping_warning: true
    cs_pin:
      ignore_pin_validation_error: true
    lambda: |-
      unsigned int co2_val = round(id(co2).state);
      unsigned int aqi_val = round(id(aqi).state);

      Color aqiRGB = aqiColor(aqi_val);
      Color co2RGB = co2Color(co2_val); 

      it.printf(40, 0, id(futura32), "%.1f°F     %.1f%%", c_to_f(id(temperature).state), id(humidity).state);
      it.printf(0, 56, id(futura32), "AQI:");
      it.printf(100, 40, id(futura60), Color(aqiRGB), " %d", aqi_val);
      it.printf(2, 120, id(futura32), "CO");
      it.printf(52, 140, id(futura16), "2");
      it.printf(62, 120, id(futura32), ":");
      it.printf(100, 104, id(futura60), Color(co2RGB), " %d", co2_val);
  

