substitutions:
  device_name: power-meter
  friendly_name: Power Meter
  board_type: adafruit_qtpy_esp32
  fqdn: power-meter.sf.aberrant.org

packages:
  device_base: !include common/common.yaml
  wifi: !include common/wifi.yaml


esphome:
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("rtzNxXXpqbD6YxZi");

ota:
  platform: esphome
  id: my_ota



sensor:
  - platform: homeassistant
    name: Power
    id: power
    entity_id: sensor.mains_power_total
#    entity_id: sensor.meter_test_sensor
    unit_of_measurement: 'W'
    internal: true
    filters:
      - calibrate_polynomial:
          degree: 5
          datapoints:
            - 0.0 -> 0
            - 200 -> 400
            - 500 -> 990
            - 1300 -> 1980
            - 1500 -> 2205
            - 2000 -> 2715
            - 3000 -> 3600
            - 3500 -> 3975
            - 4000 -> 4310
            - 4500 -> 4630
            - 5000 -> 4925            
    on_value:
      then:
        - lambda: |-
            float pct = x / 5000;
            id(meter_output).set_level(pct);

light:
  - platform: neopixelbus
    id: neopixel_led
    type: GRB
    variant: WS2812
    pin: GPIO5
    num_leds: 1
    name: "NeoPixel"

output:
  - platform: ledc
    pin: GPIO14
    id: meter_output
    frequency: 25000Hz

switch:
  - platform: gpio
    id: meter_ground
    restore_mode: ALWAYS_OFF
    pin: GPIO33