esphome:
  name: tft-test
  friendly_name: TFT Test

  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    priority: 900
    then:
      - lambda: "pinMode(7, OUTPUT); digitalWrite(7, HIGH);"


esp32:
  board: adafruit_feather_esp32s2_tft
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "EPtAM96drnjSxMRqpWySmgUhUmCv+KsTJjlUBTvvw5g="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-31125C"
    password: "cAc5JhU9nAcy"
#  manual_ip:
#    static_ip: 10.3.1.193
#    gateway: 10.3.1.2
#    subnet: 255.255.0.0

captive_portal:
    

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

  - platform: homeassistant
    id: ha_time

  # - platform:
  #   id: systime
  #   lambda: |-
  #     char str[25];
  #     time_t currTime = id(sntp_time).now().timestamp;
    

i2c:
  - id: bus_a
    sda: SDA
    scl: SCL
    frequency: 800kHz
    scan: True
    setup_priority: 700

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35
  miso_pin: GPIO37

sensor:
  - platform: homeassistant
    name: Power
    id: power
    entity_id: sensor.mains_power_total
    unit_of_measurement: 'W'
    internal: true
    # filters:
    #   - calibrate_polynomial:
    #       degree: 5
    #       datapoints:
    #         - 0.0 -> 0
    #         - 250 -> 500
    #         - 500 -> 1000
    #         - 1300 -> 2012
    #         - 1500 -> 2240
    #         - 2000 -> 2757
    #         - 3000 -> 3660
    #         - 5000 -> 5000            
    # on_value:
    #   then:
    #     - lambda: |-
    #         float pct = x / 5000;
    #         id(meter_output).set_level(pct);


light:
  - platform: neopixelbus
    id: neopixel_led
    type: GRB
    variant: WS2812
    pin: GPIO33
    num_leds: 1
    name: "NeoPixel"

output:
#  - platform: esp32_dac
#    pin: 
#      number: GPIO25
#      mode:
#        pullup: false
#        input: false
#    id: meter_output
#    zero_means_zero: true

  - platform: ledc
    pin: GPIO4
    id: meter_output
    frequency: 25000Hz

status_led:
  pin:
    number: GPIO13
    inverted: false

switch:
  - platform: gpio
    id: neopixel_power
    restore_mode: ALWAYS_ON
    pin: GPIO21



display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    backlight_pin: GPIO45
    cs_pin: GPIO42
    dc_pin: GPIO40
    reset_pin: GPIO41
    rotation: 90
    update_interval: 0.5s
    lambda: |-
      auto blue = Color(0, 0, 255);
      it.strftime(30, 0, id(futura32), "%Y-%m-%d", id(ha_time).now());
      it.strftime(0, 40, id(futura84), "%H:%M", id(ha_time).now());
  
  
  #    it.print(0, 0, id(terminus28), "Hello World!");

font:
  - file: "fonts/Futura-Medium-01.ttf"
    id: futura32
    size: 32
  - file: "fonts/Futura-Medium-01.ttf"
    id: futura48
    size: 48
  - file: "fonts/Futura-Medium-01.ttf"
    id: futura60
    size: 60
  - file: "fonts/Futura-Medium-01.ttf"
    id: futura84
    size: 84
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
  - file: "gfonts://Roboto+Mono"
    id: roboto_mono
    size: 22
  - file: "fonts/JetBrainsMono-Regular.ttf"
    id: jetbrains_mono
    size: 22
  - file: "fonts/Gomme10x20n.bdf"
    id: gomme
    size: 20
  - file: "fonts/ter-u18n.bdf"
    id: terminus18n
    size: 18
  - file: "fonts/ter-u18b.bdf"
    id: terminus18b
    size: 18    
  - file: "fonts/ter-u20n.bdf"
    id: terminus20n
  - file: "fonts/ter-u20b.bdf"
    id: terminus20b
    size: 20
  - file: "fonts/ter-u28b.bdf"
    id: terminus28
    size: 28
  - file: "fonts/ter-u32b.bdf"
    id: terminus32
    size: 36

